import { Injectable } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Observable';



@Injectable()
export class UtilsServices {
    constructor() { }

    getListOfCurrencies(): Observable<any> {
        const currArr: { value: string, desc: string }[] = [
            { value: "ALL", desc: "Albania Lek (Lek)" },
            { value: "AFN", desc: "Afghanistan Afghani (؋)" },
            { value: "ARS", desc: "Argentina Peso ($)" },
            { value: "AWG", desc: "Aruba Guilder (ƒ)" },
            { value: "AUD", desc: "Australia Dollar ($)" },
            { value: "AZN", desc: "Azerbaijan New Manat (ман)" },
            { value: "BSD", desc: "Bahamas Dollar ($)" },
            { value: "BBD", desc: "Barbados Dollar ($)" },
            { value: "BYR", desc: "Belarus Ruble (p.)" },
            { value: "BZD", desc: "Belize Dollar (BZ$)" },
            { value: "BMD", desc: "Bermuda Dollar ($)" },
            { value: "BOB", desc: "Bolivia Boliviano ($b)" },
            { value: "BAM", desc: "Bosnia and Herzegovina Convertible Marka (KM)" },
            { value: "BWP", desc: "Botswana Pula (P)" },
            { value: "BGN", desc: "Bulgaria Lev (лв)" },
            { value: "BGL", desc: "Bulgaria Lev (лв)" },
            { value: "BRL", desc: "Brazil Real (R$)" },
            { value: "BND", desc: "Brunei Darussalam Dollar ($)" },
            { value: "KHR", desc: "Cambodia Riel (៛)" },
            { value: "CAD", desc: "Canada Dollar ($)" },
            { value: "KYD", desc: "Cayman Islands Dollar ($)" },
            { value: "CLP", desc: "Chile Peso ($)" },
            { value: "CNY", desc: "China Yuan Renminbi (¥)" },
            { value: "COP", desc: "Colombia Peso ($)" },
            { value: "CRC", desc: "Costa Rica Colon (₡)" },
            { value: "HRK", desc: "Croatia Kuna (kn)" },
            { value: "CUP", desc: "Cuba Peso (₱)" },
            { value: "CZK", desc: "Czech Republic Koruna (Kč)" },
            { value: "DKK", desc: "Denmark Krone (kr)" },
            { value: "DOP", desc: "Dominican Republic Peso (RD$)" },
            { value: "XCD", desc: "East Caribbean Dollar ($)" },
            { value: "EGP", desc: "Egypt Pound (£)" },
            { value: "SVC", desc: "El Salvador Colon ($)" },
            { value: "EEK", desc: "Estonia Kroon (kr)" },
            { value: "EUR", desc: "Euro Member Countries (€)" },
            { value: "FKP", desc: "Falkland Islands (Malvinas) Pound (£)" },
            { value: "FJD", desc: "Fiji Dollar ($)" },
            { value: "GHC", desc: "Ghana Cedis (¢)" },
            { value: "GIP", desc: "Gibraltar Pound (£)" },
            { value: "GTQ", desc: "Guatemala Quetzal (Q)" },
            { value: "GGP", desc: "Guernsey Pound (£)" },
            { value: "GYD", desc: "Guyana Dollar ($)" },
            { value: "HNL", desc: "Honduras Lempira (L)" },
            { value: "HKD", desc: "Hong Kong Dollar ($)" },
            { value: "HUF", desc: "Hungary Forint (Ft)" },
            { value: "ISK", desc: "Iceland Krona (kr)" },
            { value: "INR", desc: "Indian Rupee (₹)" },
            { value: "IDR", desc: "Indonesia Rupiah (Rp)" },
            { value: "IRR", desc: "Iran Rial (﷼)" },
            { value: "IMP", desc: "Isle of Man Pound (£)" },
            { value: "ILS", desc: "Israel Shekel (₪)" },
            { value: "JMD", desc: "Jamaica Dollar (J$)" },
            { value: "JPY", desc: "Japan Yen (¥)" },
            { value: "JEP", desc: "Jersey Pound (£)" },
            { value: "KZT", desc: "Kazakhstan Tenge (лв)" },
            { value: "KPW", desc: "Korea (North) Won (₩)" },
            { value: "KRW", desc: "Korea (South) Won (₩)" },
            { value: "KGS", desc: "Kyrgyzstan Som (лв)" },
            { value: "LAK", desc: "Laos Kip (₭)" },
            { value: "LVL", desc: "Latvia Lat (Ls)" },
            { value: "LBP", desc: "Lebanon Pound (£)" },
            { value: "LRD", desc: "Liberia Dollar ($)" },
            { value: "LTL", desc: "Lithuania Litas (Lt)" },
            { value: "MKD", desc: "Macedonia Denar (ден)" },
            { value: "MYR", desc: "Malaysia Ringgit (RM)" },
            { value: "MUR", desc: "Mauritius Rupee (₨)" },
            { value: "MXN", desc: "Mexico Peso ($)" },
            { value: "MNT", desc: "Mongolia Tughrik (₮)" },
            { value: "MZN", desc: "Mozambique Metical (MT)" },
            { value: "NAD", desc: "Namibia Dollar ($)" },
            { value: "NPR", desc: "Nepal Rupee (₨)" },
            { value: "ANG", desc: "Netherlands Antilles Guilder (ƒ)" },
            { value: "NZD", desc: "New Zealand Dollar ($)" },
            { value: "NIO", desc: "Nicaragua Cordoba (C$)" },
            { value: "NGN", desc: "Nigeria Naira (₦)" },
            { value: "NOK", desc: "Norway Krone (kr)" },
            { value: "OMR", desc: "Oman Rial (﷼)" },
            { value: "PKR", desc: "Pakistan Rupee (₨)" },
            { value: "PAB", desc: "Panama Balboa (B/.)" },
            { value: "PYG", desc: "Paraguay Guarani (Gs)" },
            { value: "PEN", desc: "Peru Nuevo Sol (S/.)" },
            { value: "PHP", desc: "Philippines Peso (₱)" },
            { value: "PLN", desc: "Poland Zloty (zł)" },
            { value: "QAR", desc: "Qatar Riyal (﷼)" },
            { value: "RON", desc: "Romania New Leu (lei)" },
            { value: "RUB", desc: "Russia Ruble (руб)" },
            { value: "SHP", desc: "Saint Helena Pound (£)" },
            { value: "SAR", desc: "Saudi Arabia Riyal (﷼)" },
            { value: "RSD", desc: "Serbia Dinar (Дин.)" },
            { value: "SCR", desc: "Seychelles Rupee (₨)" },
            { value: "SGD", desc: "Singapore Dollar ($)" },
            { value: "SBD", desc: "Solomon Islands Dollar ($)" },
            { value: "SOS", desc: "Somalia Shilling (S)" },
            { value: "ZAR", desc: "South Africa Rand (R)" },
            { value: "LKR", desc: "Sri Lanka Rupee (₨)" },
            { value: "SEK", desc: "Sweden Krona (kr)" },
            { value: "CHF", desc: "Switzerland Franc (CHF)" },
            { value: "SRD", desc: "Suriname Dollar ($)" },
            { value: "SYP", desc: "Syria Pound (£)" },
            { value: "TWD", desc: "Taiwan New Dollar (NT$)" },
            { value: "THB", desc: "Thailand Baht (฿)" },
            { value: "TTD", desc: "Trinidad and Tobago Dollar (TT$)" },
            { value: "TRY", desc: "Turkey Lira (TL)" },
            { value: "TRL", desc: "Turkey Lira (₤)" },
            { value: "TVD", desc: "Tuvalu Dollar ($)" },
            { value: "UAH", desc: "Ukraine Hryvna (₴)" },
            { value: "GBP", desc: "United Kingdom Pound (£)" },
            { value: "USD", desc: "United States Dollar ($)" },
            { value: "UYU", desc: "Uruguay Peso ($U)" },
            { value: "UZS", desc: "Uzbekistan Som (лв)" },
            { value: "VEF", desc: "Venezuela Bolivar Fuerte (Bs)" },
            { value: "VND", desc: "Viet Nam Dong (₫)" },
            { value: "YER", desc: "Yemen Rial (﷼)" },
            { value: "ZWD", desc: "Zimbabwe Dollar (Z$)" }
        ];



        return new Observable(observer => {
            observer.next(currArr);
            observer.complete();
        });
    }

    getListOfCountries(): Observable<any> {
        const currArr: { value: string, desc: string }[] = [

            { value: "af", desc: "Afghanistan" },
            { value: "ax", desc: "Aland Islands" },
            { value: "al", desc: "Albania" },
            { value: "dz", desc: "Algeria" },
            { value: "as", desc: "American Samoa" },
            { value: "ad", desc: "Andorra" },
            { value: "ao", desc: "Angola" },
            { value: "ai", desc: "Anguilla" },
            { value: "ag", desc: "Antigua" },
            { value: "ar", desc: "Argentina" },
            { value: "am", desc: "Armenia" },
            { value: "aw", desc: "Aruba" },
            { value: "au", desc: "Australia" },
            { value: "at", desc: "Austria" },
            { value: "az", desc: "Azerbaijan" },
            { value: "bs", desc: "Bahamas" },
            { value: "bh", desc: "Bahrain" },
            { value: "bd", desc: "Bangladesh" },
            { value: "bb", desc: "Barbados" },
            { value: "by", desc: "Belarus" },
            { value: "be", desc: "Belgium" },
            { value: "bz", desc: "Belize" },
            { value: "bj", desc: "Benin" },
            { value: "bm", desc: "Bermuda" },
            { value: "bt", desc: "Bhutan" },
            { value: "bo", desc: "Bolivia" },
            { value: "ba", desc: "Bosnia" },
            { value: "bw", desc: "Botswana" },
            { value: "bv", desc: "Bouvet Island" },
            { value: "br", desc: "Brazil" },
            { value: "vg", desc: "British Virgin Islands" },
            { value: "bn", desc: "Brunei" },
            { value: "bg", desc: "Bulgaria" },
            { value: "bf", desc: "Burkina Faso" },
            { value: "mm", desc: "Burma" },
            { value: "bi", desc: "Burundi" },
            { value: "tc", desc: "Caicos Islands" },
            { value: "kh", desc: "Cambodia" },
            { value: "cm", desc: "Cameroon" },
            { value: "ca", desc: "Canada" },
            { value: "cv", desc: "Cape Verde" },
            { value: "ky", desc: "Cayman Islands" },
            { value: "cf", desc: "Central African Republic" },
            { value: "td", desc: "Chad" },
            { value: "cl", desc: "Chile" },
            { value: "cn", desc: "China" },
            { value: "cx", desc: "Christmas Island" },
            { value: "cc", desc: "Cocos Islands" },
            { value: "co", desc: "Colombia" },
            { value: "km", desc: "Comoros" },
            { value: "cg", desc: "Congo Brazzaville" },
            { value: "cd", desc: "Congo" },
            { value: "ck", desc: "Cook Islands" },
            { value: "cr", desc: "Costa Rica" },
            { value: "ci", desc: "Cote Divoire" },
            { value: "hr", desc: "Croatia" },
            { value: "cu", desc: "Cuba" },
            { value: "cy", desc: "Cyprus" },
            { value: "cz", desc: "Czech Republic" },
            { value: "dk", desc: "Denmark" },
            { value: "dj", desc: "Djibouti" },
            { value: "dm", desc: "Dominica" },
            { value: "do", desc: "Dominican Republic" },
            { value: "ec", desc: "Ecuador" },
            { value: "eg", desc: "Egypt" },
            { value: "sv", desc: "El Salvador" },
            { value: "gb", desc: "England" },
            { value: "gq", desc: "Equatorial Guinea" },
            { value: "er", desc: "Eritrea" },
            { value: "ee", desc: "Estonia" },
            { value: "et", desc: "Ethiopia" },
            { value: "eu", desc: "European Union" },
            { value: "fk", desc: "Falkland Islands" },
            { value: "fo", desc: "Faroe Islands" },
            { value: "fj", desc: "Fiji" },
            { value: "fi", desc: "Finland" },
            { value: "fr", desc: "France" },
            { value: "gf", desc: "French Guiana" },
            { value: "pf", desc: "French Polynesia" },
            { value: "tf", desc: "French Territories" },
            { value: "ga", desc: "Gabon" },
            { value: "gm", desc: "Gambia" },
            { value: "ge", desc: "Georgia" },
            { value: "de", desc: "Germany" },
            { value: "gh", desc: "Ghana" },
            { value: "gi", desc: "Gibraltar" },
            { value: "gr", desc: "Greece" },
            { value: "gl", desc: "Greenland" },
            { value: "gd", desc: "Grenada" },
            { value: "gp", desc: "Guadeloupe" },
            { value: "gu", desc: "Guam" },
            { value: "gt", desc: "Guatemala" },
            { value: "gw", desc: "Guinea-Bissau" },
            { value: "gn", desc: "Guinea" },
            { value: "gy", desc: "Guyana" },
            { value: "ht", desc: "Haiti" },
            { value: "hm", desc: "Heard Island" },
            { value: "hn", desc: "Honduras" },
            { value: "hk", desc: "Hong Kong" },
            { value: "hu", desc: "Hungary" },
            { value: "is", desc: "Iceland" },
            { value: "in", desc: "India" },
            { value: "io", desc: "Indian Ocean Territory" },
            { value: "id", desc: "Indonesia" },
            { value: "ir", desc: "Iran" },
            { value: "iq", desc: "Iraq" },
            { value: "ie", desc: "Ireland" },
            { value: "il", desc: "Israel" },
            { value: "it", desc: "Italy" },
            { value: "jm", desc: "Jamaica" },
            { value: "jp", desc: "Japan" },
            { value: "jo", desc: "Jordan" },
            { value: "kz", desc: "Kazakhstan" },
            { value: "ke", desc: "Kenya" },
            { value: "ki", desc: "Kiribati" },
            { value: "kw", desc: "Kuwait" },
            { value: "kg", desc: "Kyrgyzstan" },
            { value: "la", desc: "Laos" },
            { value: "lv", desc: "Latvia" },
            { value: "lb", desc: "Lebanon" },
            { value: "ls", desc: "Lesotho" },
            { value: "lr", desc: "Liberia" },
            { value: "ly", desc: "Libya" },
            { value: "li", desc: "Liechtenstein" },
            { value: "lt", desc: "Lithuania" },
            { value: "lu", desc: "Luxembourg" },
            { value: "mo", desc: "Macau" },
            { value: "mk", desc: "Macedonia" },
            { value: "mg", desc: "Madagascar" },
            { value: "mw", desc: "Malawi" },
            { value: "my", desc: "Malaysia" },
            { value: "mv", desc: "Maldives" },
            { value: "ml", desc: "Mali" },
            { value: "mt", desc: "Malta" },
            { value: "mh", desc: "Marshall Islands" },
            { value: "mq", desc: "Martinique" },
            { value: "mr", desc: "Mauritania" },
            { value: "mu", desc: "Mauritius" },
            { value: "yt", desc: "Mayotte" },
            { value: "mx", desc: "Mexico" },
            { value: "fm", desc: "Micronesia" },
            { value: "md", desc: "Moldova" },
            { value: "mc", desc: "Monaco" },
            { value: "mn", desc: "Mongolia" },
            { value: "me", desc: "Montenegro" },
            { value: "ms", desc: "Montserrat" },
            { value: "ma", desc: "Morocco" },
            { value: "mz", desc: "Mozambique" },
            { value: "na", desc: "Namibia" },
            { value: "nr", desc: "Nauru" },
            { value: "np", desc: "Nepal" },
            { value: "an", desc: "Netherlands Antilles" },
            { value: "nl", desc: "Netherlands" },
            { value: "nc", desc: "New Caledonia" },
            { value: "pg", desc: "New Guinea" },
            { value: "nz", desc: "New Zealand" },
            { value: "ni", desc: "Nicaragua" },
            { value: "ne", desc: "Niger" },
            { value: "ng", desc: "Nigeria" },
            { value: "nu", desc: "Niue" },
            { value: "nf", desc: "Norfolk Island" },
            { value: "kp", desc: "North Korea" },
            { value: "mp", desc: "Northern Mariana Islands" },
            { value: "no", desc: "Norway" },
            { value: "om", desc: "Oman" },
            { value: "pk", desc: "Pakistan" },
            { value: "pw", desc: "Palau" },
            { value: "ps", desc: "Palestine" },
            { value: "pa", desc: "Panama" },
            { value: "py", desc: "Paraguay" },
            { value: "pe", desc: "Peru" },
            { value: "ph", desc: "Philippines" },
            { value: "pn", desc: "Pitcairn Islands" },
            { value: "pl", desc: "Poland" },
            { value: "pt", desc: "Portugal" },
            { value: "pr", desc: "Puerto Rico" },
            { value: "qa", desc: "Qatar" },
            { value: "re", desc: "Reunion" },
            { value: "ro", desc: "Romania" },
            { value: "ru", desc: "Russia" },
            { value: "rw", desc: "Rwanda" },
            { value: "sh", desc: "Saint Helena" },
            { value: "kn", desc: "Saint Kitts and Nevis" },
            { value: "lc", desc: "Saint Lucia" },
            { value: "pm", desc: "Saint Pierre" },
            { value: "vc", desc: "Saint Vincent" },
            { value: "ws", desc: "Samoa" },
            { value: "sm", desc: "San Marino" },
            { value: "gs", desc: "Sandwich Islands" },
            { value: "st", desc: "Sao Tome" },
            { value: "sa", desc: "Saudi Arabia" },
            { value: "sn", desc: "Senegal" },
            { value: "cs", desc: "Serbia" },
            { value: "rs", desc: "Serbia" },
            { value: "sc", desc: "Seychelles" },
            { value: "sl", desc: "Sierra Leone" },
            { value: "sg", desc: "Singapore" },
            { value: "sk", desc: "Slovakia" },
            { value: "si", desc: "Slovenia" },
            { value: "sb", desc: "Solomon Islands" },
            { value: "so", desc: "Somalia" },
            { value: "za", desc: "South Africa" },
            { value: "kr", desc: "South Korea" },
            { value: "es", desc: "Spain" },
            { value: "lk", desc: "Sri Lanka" },
            { value: "sd", desc: "Sudan" },
            { value: "sr", desc: "Suriname" },
            { value: "sj", desc: "Svalbard" },
            { value: "sz", desc: "Swaziland" },
            { value: "se", desc: "Sweden" },
            { value: "ch", desc: "Switzerland" },
            { value: "sy", desc: "Syria" },
            { value: "tw", desc: "Taiwan" },
            { value: "tj", desc: "Tajikistan" },
            { value: "tz", desc: "Tanzania" },
            { value: "th", desc: "Thailand" },
            { value: "tl", desc: "Timorleste" },
            { value: "tg", desc: "Togo" },
            { value: "tk", desc: "Tokelau" },
            { value: "to", desc: "Tonga" },
            { value: "tt", desc: "Trinidad" },
            { value: "tn", desc: "Tunisia" },
            { value: "tr", desc: "Turkey" },
            { value: "tm", desc: "Turkmenistan" },
            { value: "tv", desc: "Tuvalu" },
            { value: "ug", desc: "Uganda" },
            { value: "ua", desc: "Ukraine" },
            { value: "ae", desc: "United Arab Emirates" },
            { value: "us", desc: "United States" },
            { value: "uy", desc: "Uruguay" },
            { value: "um", desc: "Us Minor Islands" },
            { value: "vi", desc: "Us Virgin Islands" },
            { value: "uz", desc: "Uzbekistan" },
            { value: "vu", desc: "Vanuatu" },
            { value: "va", desc: "Vatican City" },
            { value: "ve", desc: "Venezuela" },
            { value: "vn", desc: "Vietnam" },
            { value: "wf", desc: "Wallis and Futuna" },
            { value: "eh", desc: "Western Sahara" },
            { value: "ye", desc: "Yemen" },
            { value: "zm", desc: "Zambia" },
            { value: "zw", desc: "Zimbabwe" }


        ];



        return new Observable(observer => {
            observer.next(currArr);
            observer.complete();
        });
    }





}