import { Injectable } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Observable';



@Injectable()
export class UtilsServices {
    constructor() { }

    getListOfCurrencies(): Observable<any> {
        const currArr: { value: string, desc: string }[] = [
            { value: "ALL", desc: "Albania Lek (Lek)" },
            { value: "AFN", desc: "Afghanistan Afghani (؋)" },
            { value: "ARS", desc: "Argentina Peso ($)" },
            { value: "AWG", desc: "Aruba Guilder (ƒ)" },
            { value: "AUD", desc: "Australia Dollar ($)" },
            { value: "AZN", desc: "Azerbaijan New Manat (ман)" },
            { value: "BSD", desc: "Bahamas Dollar ($)" },
            { value: "BBD", desc: "Barbados Dollar ($)" },
            { value: "BYR", desc: "Belarus Ruble (p.)" },
            { value: "BZD", desc: "Belize Dollar (BZ$)" },
            { value: "BMD", desc: "Bermuda Dollar ($)" },
            { value: "BOB", desc: "Bolivia Boliviano ($b)" },
            { value: "BAM", desc: "Bosnia and Herzegovina Convertible Marka (KM)" },
            { value: "BWP", desc: "Botswana Pula (P)" },
            { value: "BGN", desc: "Bulgaria Lev (лв)" },
            { value: "BGL", desc: "Bulgaria Lev (лв)" },
            { value: "BRL", desc: "Brazil Real (R$)" },
            { value: "BND", desc: "Brunei Darussalam Dollar ($)" },
            { value: "KHR", desc: "Cambodia Riel (៛)" },
            { value: "CAD", desc: "Canada Dollar ($)" },
            { value: "KYD", desc: "Cayman Islands Dollar ($)" },
            { value: "CLP", desc: "Chile Peso ($)" },
            { value: "CNY", desc: "China Yuan Renminbi (¥)" },
            { value: "COP", desc: "Colombia Peso ($)" },
            { value: "CRC", desc: "Costa Rica Colon (₡)" },
            { value: "HRK", desc: "Croatia Kuna (kn)" },
            { value: "CUP", desc: "Cuba Peso (₱)" },
            { value: "CZK", desc: "Czech Republic Koruna (Kč)" },
            { value: "DKK", desc: "Denmark Krone (kr)" },
            { value: "DOP", desc: "Dominican Republic Peso (RD$)" },
            { value: "XCD", desc: "East Caribbean Dollar ($)" },
            { value: "EGP", desc: "Egypt Pound (£)" },
            { value: "SVC", desc: "El Salvador Colon ($)" },
            { value: "EEK", desc: "Estonia Kroon (kr)" },
            { value: "EUR", desc: "Euro Member Countries (€)" },
            { value: "FKP", desc: "Falkland Islands (Malvinas) Pound (£)" },
            { value: "FJD", desc: "Fiji Dollar ($)" },
            { value: "GHC", desc: "Ghana Cedis (¢)" },
            { value: "GIP", desc: "Gibraltar Pound (£)" },
            { value: "GTQ", desc: "Guatemala Quetzal (Q)" },
            { value: "GGP", desc: "Guernsey Pound (£)" },
            { value: "GYD", desc: "Guyana Dollar ($)" },
            { value: "HNL", desc: "Honduras Lempira (L)" },
            { value: "HKD", desc: "Hong Kong Dollar ($)" },
            { value: "HUF", desc: "Hungary Forint (Ft)" },
            { value: "ISK", desc: "Iceland Krona (kr)" },
            { value: "INR", desc: "Indian Rupee (₹)" },
            { value: "IDR", desc: "Indonesia Rupiah (Rp)" },
            { value: "IRR", desc: "Iran Rial (﷼)" },
            { value: "IMP", desc: "Isle of Man Pound (£)" },
            { value: "ILS", desc: "Israel Shekel (₪)" },
            { value: "JMD", desc: "Jamaica Dollar (J$)" },
            { value: "JPY", desc: "Japan Yen (¥)" },
            { value: "JEP", desc: "Jersey Pound (£)" },
            { value: "KZT", desc: "Kazakhstan Tenge (лв)" },
            { value: "KPW", desc: "Korea (North) Won (₩)" },
            { value: "KRW", desc: "Korea (South) Won (₩)" },
            { value: "KGS", desc: "Kyrgyzstan Som (лв)" },
            { value: "LAK", desc: "Laos Kip (₭)" },
            { value: "LVL", desc: "Latvia Lat (Ls)" },
            { value: "LBP", desc: "Lebanon Pound (£)" },
            { value: "LRD", desc: "Liberia Dollar ($)" },
            { value: "LTL", desc: "Lithuania Litas (Lt)" },
            { value: "MKD", desc: "Macedonia Denar (ден)" },
            { value: "MYR", desc: "Malaysia Ringgit (RM)" },
            { value: "MUR", desc: "Mauritius Rupee (₨)" },
            { value: "MXN", desc: "Mexico Peso ($)" },
            { value: "MNT", desc: "Mongolia Tughrik (₮)" },
            { value: "MZN", desc: "Mozambique Metical (MT)" },
            { value: "NAD", desc: "Namibia Dollar ($)" },
            { value: "NPR", desc: "Nepal Rupee (₨)" },
            { value: "ANG", desc: "Netherlands Antilles Guilder (ƒ)" },
            { value: "NZD", desc: "New Zealand Dollar ($)" },
            { value: "NIO", desc: "Nicaragua Cordoba (C$)" },
            { value: "NGN", desc: "Nigeria Naira (₦)" },
            { value: "NOK", desc: "Norway Krone (kr)" },
            { value: "OMR", desc: "Oman Rial (﷼)" },
            { value: "PKR", desc: "Pakistan Rupee (₨)" },
            { value: "PAB", desc: "Panama Balboa (B/.)" },
            { value: "PYG", desc: "Paraguay Guarani (Gs)" },
            { value: "PEN", desc: "Peru Nuevo Sol (S/.)" },
            { value: "PHP", desc: "Philippines Peso (₱)" },
            { value: "PLN", desc: "Poland Zloty (zł)" },
            { value: "QAR", desc: "Qatar Riyal (﷼)" },
            { value: "RON", desc: "Romania New Leu (lei)" },
            { value: "RUB", desc: "Russia Ruble (руб)" },
            { value: "SHP", desc: "Saint Helena Pound (£)" },
            { value: "SAR", desc: "Saudi Arabia Riyal (﷼)" },
            { value: "RSD", desc: "Serbia Dinar (Дин.)" },
            { value: "SCR", desc: "Seychelles Rupee (₨)" },
            { value: "SGD", desc: "Singapore Dollar ($)" },
            { value: "SBD", desc: "Solomon Islands Dollar ($)" },
            { value: "SOS", desc: "Somalia Shilling (S)" },
            { value: "ZAR", desc: "South Africa Rand (R)" },
            { value: "LKR", desc: "Sri Lanka Rupee (₨)" },
            { value: "SEK", desc: "Sweden Krona (kr)" },
            { value: "CHF", desc: "Switzerland Franc (CHF)" },
            { value: "SRD", desc: "Suriname Dollar ($)" },
            { value: "SYP", desc: "Syria Pound (£)" },
            { value: "TWD", desc: "Taiwan New Dollar (NT$)" },
            { value: "THB", desc: "Thailand Baht (฿)" },
            { value: "TTD", desc: "Trinidad and Tobago Dollar (TT$)" },
            { value: "TRY", desc: "Turkey Lira (TL)" },
            { value: "TRL", desc: "Turkey Lira (₤)" },
            { value: "TVD", desc: "Tuvalu Dollar ($)" },
            { value: "UAH", desc: "Ukraine Hryvna (₴)" },
            { value: "GBP", desc: "United Kingdom Pound (£)" },
            { value: "USD", desc: "United States Dollar ($)" },
            { value: "UYU", desc: "Uruguay Peso ($U)" },
            { value: "UZS", desc: "Uzbekistan Som (лв)" },
            { value: "VEF", desc: "Venezuela Bolivar Fuerte (Bs)" },
            { value: "VND", desc: "Viet Nam Dong (₫)" },
            { value: "YER", desc: "Yemen Rial (﷼)" },
            { value: "ZWD", desc: "Zimbabwe Dollar (Z$)" }
        ];



        return new Observable(observer => {
            observer.next(currArr);
            observer.complete();
        });
    }


    getListofBirthYear(): Observable<any> {
        const birthYearArr: { value: string }[] = [
            { value: "2017" },
            { value: "2016" },
            { value: "2015" },
            { value: "2014" },
            { value: "2013" },
            { value: "2012" },
            { value: "2011" },
            { value: "2010" },
            { value: "2009" },
            { value: "2008" },
            { value: "2007" },
            { value: "2006" },
            { value: "2005" },
            { value: "2004" },
            { value: "2003" },
            { value: "2002" },
            { value: "2001" },
            { value: "2000" },
            { value: "1999" },
            { value: "1998" },
            { value: "1997" },
            { value: "1996" },
            { value: "1995" },
            { value: "1994" },
            { value: "1993" },
            { value: "1992" },
            { value: "1991" },
            { value: "1990" },
            { value: "1989" },
            { value: "1988" },
            { value: "1987" },
            { value: "1986" },
            { value: "1985" },
            { value: "1984" },
            { value: "1983" },
            { value: "1982" },
            { value: "1981" },
            { value: "1980" },
            { value: "1979" },
            { value: "1978" },
            { value: "1977" },
            { value: "1976" },
            { value: "1975" },
            { value: "1974" },
            { value: "1973" },
            { value: "1972" },
            { value: "1971" },
            { value: "1970" },
            { value: "1969" },
            { value: "1968" },
            { value: "1967" },
            { value: "1966" },
            { value: "1965" },
            { value: "1964" },
            { value: "1963" },
            { value: "1962" },
            { value: "1961" },
            { value: "1960" },
            { value: "1959" },
            { value: "1958" },
            { value: "1957" },
            { value: "1956" },
            { value: "1955" },
            { value: "1954" },
            { value: "1953" },
            { value: "1952" },
            { value: "1951" },
            { value: "1950" },
            { value: "1949" },
            { value: "1948" },
            { value: "1947" },
            { value: "1946" },
            { value: "1945" },
            { value: "1944" },
            { value: "1943" },
            { value: "1942" },
            { value: "1941" },
            { value: "1940" },
            { value: "1939" },
            { value: "1938" },
            { value: "1937" },
            { value: "1936" },
            { value: "1935" },
            { value: "1934" },
            { value: "1933" },
            { value: "1932" },
            { value: "1931" },
            { value: "1930" },
            { value: "1929" },
            { value: "1928" },
            { value: "1927" },
            { value: "1926" },
            { value: "1925" },
            { value: "1924" },
            { value: "1923" },
            { value: "1922" },
            { value: "1921" },
            { value: "1920" }

        ];



        return new Observable(observer => {
            observer.next(birthYearArr);
            observer.complete();
        });
    }




    getListOfCountries(): Observable<any> {
        const cntFlagArr: { value: string, desc: string, flag: string }[] = [

            { value: "af", desc: "Afghanistan", flag: 'af flag' },
            { value: "ax", desc: "Aland Islands", flag: '' },
            { value: "al", desc: "Albania", flag: '' },
            { value: "dz", desc: "Algeria", flag: '' },
            { value: "as", desc: "American Samoa", flag: '' },
            { value: "ad", desc: "Andorra", flag: '' },
            { value: "ao", desc: "Angola", flag: '' },
            { value: "ai", desc: "Anguilla", flag: '' },
            { value: "ag", desc: "Antigua", flag: '' },
            { value: "ar", desc: "Argentina", flag: '' },
            { value: "am", desc: "Armenia", flag: '' },
            { value: "aw", desc: "Aruba", flag: '' },
            { value: "au", desc: "Australia", flag: '' },
            { value: "at", desc: "Austria", flag: '' },
            { value: "az", desc: "Azerbaijan", flag: '' },
            { value: "bs", desc: "Bahamas", flag: '' },
            { value: "bh", desc: "Bahrain", flag: '' },
            { value: "bd", desc: "Bangladesh", flag: '' },
            { value: "bb", desc: "Barbados", flag: '' },
            { value: "by", desc: "Belarus", flag: '' },
            { value: "be", desc: "Belgium", flag: '' },
            { value: "bz", desc: "Belize", flag: '' },
            { value: "bj", desc: "Benin", flag: '' },
            { value: "bm", desc: "Bermuda", flag: '' },
            { value: "bt", desc: "Bhutan", flag: '' },
            { value: "bo", desc: "Bolivia", flag: '' },
            { value: "ba", desc: "Bosnia", flag: '' },
            { value: "bw", desc: "Botswana", flag: '' },
            { value: "bv", desc: "Bouvet Island", flag: '' },
            { value: "br", desc: "Brazil", flag: '' },
            { value: "vg", desc: "British Virgin Islands", flag: '' },
            { value: "bn", desc: "Brunei", flag: '' },
            { value: "bg", desc: "Bulgaria", flag: '' },
            { value: "bf", desc: "Burkina Faso", flag: '' },
            { value: "mm", desc: "Burma", flag: '' },
            { value: "bi", desc: "Burundi", flag: '' },
            { value: "tc", desc: "Caicos Islands", flag: '' },
            { value: "kh", desc: "Cambodia", flag: '' },
            { value: "cm", desc: "Cameroon", flag: '' },
            { value: "ca", desc: "Canada", flag: '' },
            { value: "cv", desc: "Cape Verde", flag: '' },
            { value: "ky", desc: "Cayman Islands", flag: '' },
            { value: "cf", desc: "Central African Republic", flag: '' },
            { value: "td", desc: "Chad", flag: '' },
            { value: "cl", desc: "Chile", flag: '' },
            { value: "cn", desc: "China", flag: '' },
            { value: "cx", desc: "Christmas Island", flag: '' },
            { value: "cc", desc: "Cocos Islands", flag: '' },
            { value: "co", desc: "Colombia", flag: '' },
            { value: "km", desc: "Comoros", flag: '' },
            { value: "cg", desc: "Congo Brazzaville", flag: '' },
            { value: "cd", desc: "Congo", flag: '' },
            { value: "ck", desc: "Cook Islands", flag: '' },
            { value: "cr", desc: "Costa Rica", flag: '' },
            { value: "ci", desc: "Cote Divoire", flag: '' },
            { value: "hr", desc: "Croatia", flag: '' },
            { value: "cu", desc: "Cuba", flag: '' },
            { value: "cy", desc: "Cyprus", flag: '' },
            { value: "cz", desc: "Czech Republic", flag: '' },
            { value: "dk", desc: "Denmark", flag: '' },
            { value: "dj", desc: "Djibouti", flag: '' },
            { value: "dm", desc: "Dominica", flag: '' },
            { value: "do", desc: "Dominican Republic", flag: '' },
            { value: "ec", desc: "Ecuador", flag: '' },
            { value: "eg", desc: "Egypt", flag: '' },
            { value: "sv", desc: "El Salvador", flag: '' },
            { value: "gb", desc: "England", flag: '' },
            { value: "gq", desc: "Equatorial Guinea", flag: '' },
            { value: "er", desc: "Eritrea", flag: '' },
            { value: "ee", desc: "Estonia", flag: '' },
            { value: "et", desc: "Ethiopia", flag: '' },
            { value: "eu", desc: "European Union", flag: '' },
            { value: "fk", desc: "Falkland Islands", flag: '' },
            { value: "fo", desc: "Faroe Islands", flag: '' },
            { value: "fj", desc: "Fiji", flag: '' },
            { value: "fi", desc: "Finland", flag: '' },
            { value: "fr", desc: "France", flag: '' },
            { value: "gf", desc: "French Guiana", flag: '' },
            { value: "pf", desc: "French Polynesia", flag: '' },
            { value: "tf", desc: "French Territories", flag: '' },
            { value: "ga", desc: "Gabon", flag: '' },
            { value: "gm", desc: "Gambia", flag: '' },
            { value: "ge", desc: "Georgia", flag: '' },
            { value: "de", desc: "Germany", flag: '' },
            { value: "gh", desc: "Ghana", flag: '' },
            { value: "gi", desc: "Gibraltar", flag: '' },
            { value: "gr", desc: "Greece", flag: '' },
            { value: "gl", desc: "Greenland", flag: '' },
            { value: "gd", desc: "Grenada", flag: '' },
            { value: "gp", desc: "Guadeloupe", flag: '' },
            { value: "gu", desc: "Guam", flag: '' },
            { value: "gt", desc: "Guatemala", flag: '' },
            { value: "gw", desc: "Guinea-Bissau", flag: '' },
            { value: "gn", desc: "Guinea", flag: '' },
            { value: "gy", desc: "Guyana", flag: '' },
            { value: "ht", desc: "Haiti", flag: '' },
            { value: "hm", desc: "Heard Island", flag: '' },
            { value: "hn", desc: "Honduras", flag: '' },
            { value: "hk", desc: "Hong Kong", flag: '' },
            { value: "hu", desc: "Hungary", flag: '' },
            { value: "is", desc: "Iceland", flag: '' },
            { value: "in", desc: "India", flag: '' },
            { value: "io", desc: "Indian Ocean Territory", flag: '' },
            { value: "id", desc: "Indonesia", flag: '' },
            { value: "ir", desc: "Iran", flag: '' },
            { value: "iq", desc: "Iraq", flag: '' },
            { value: "ie", desc: "Ireland", flag: '' },
            { value: "il", desc: "Israel", flag: '' },
            { value: "it", desc: "Italy", flag: '' },
            { value: "jm", desc: "Jamaica", flag: '' },
            { value: "jp", desc: "Japan", flag: '' },
            { value: "jo", desc: "Jordan", flag: '' },
            { value: "kz", desc: "Kazakhstan", flag: '' },
            { value: "ke", desc: "Kenya", flag: '' },
            { value: "ki", desc: "Kiribati", flag: '' },
            { value: "kw", desc: "Kuwait", flag: '' },
            { value: "kg", desc: "Kyrgyzstan", flag: '' },
            { value: "la", desc: "Laos", flag: '' },
            { value: "lv", desc: "Latvia", flag: '' },
            { value: "lb", desc: "Lebanon", flag: '' },
            { value: "ls", desc: "Lesotho", flag: '' },
            { value: "lr", desc: "Liberia", flag: '' },
            { value: "ly", desc: "Libya", flag: '' },
            { value: "li", desc: "Liechtenstein", flag: '' },
            { value: "lt", desc: "Lithuania", flag: '' },
            { value: "lu", desc: "Luxembourg", flag: '' },
            { value: "mo", desc: "Macau", flag: '' },
            { value: "mk", desc: "Macedonia", flag: '' },
            { value: "mg", desc: "Madagascar", flag: '' },
            { value: "mw", desc: "Malawi", flag: '' },
            { value: "my", desc: "Malaysia", flag: '' },
            { value: "mv", desc: "Maldives", flag: '' },
            { value: "ml", desc: "Mali", flag: '' },
            { value: "mt", desc: "Malta", flag: '' },
            { value: "mh", desc: "Marshall Islands", flag: '' },
            { value: "mq", desc: "Martinique", flag: '' },
            { value: "mr", desc: "Mauritania", flag: '' },
            { value: "mu", desc: "Mauritius", flag: '' },
            { value: "yt", desc: "Mayotte", flag: '' },
            { value: "mx", desc: "Mexico", flag: '' },
            { value: "fm", desc: "Micronesia", flag: '' },
            { value: "md", desc: "Moldova", flag: '' },
            { value: "mc", desc: "Monaco", flag: '' },
            { value: "mn", desc: "Mongolia", flag: '' },
            { value: "me", desc: "Montenegro", flag: '' },
            { value: "ms", desc: "Montserrat", flag: '' },
            { value: "ma", desc: "Morocco", flag: '' },
            { value: "mz", desc: "Mozambique", flag: '' },
            { value: "na", desc: "Namibia", flag: '' },
            { value: "nr", desc: "Nauru", flag: '' },
            { value: "np", desc: "Nepal", flag: '' },
            { value: "an", desc: "Netherlands Antilles", flag: '' },
            { value: "nl", desc: "Netherlands", flag: '' },
            { value: "nc", desc: "New Caledonia", flag: '' },
            { value: "pg", desc: "New Guinea", flag: '' },
            { value: "nz", desc: "New Zealand", flag: '' },
            { value: "ni", desc: "Nicaragua", flag: '' },
            { value: "ne", desc: "Niger", flag: '' },
            { value: "ng", desc: "Nigeria", flag: '' },
            { value: "nu", desc: "Niue", flag: '' },
            { value: "nf", desc: "Norfolk Island", flag: '' },
            { value: "kp", desc: "North Korea", flag: '' },
            { value: "mp", desc: "Northern Mariana Islands", flag: '' },
            { value: "no", desc: "Norway", flag: '' },
            { value: "om", desc: "Oman", flag: '' },
            { value: "pk", desc: "Pakistan", flag: '' },
            { value: "pw", desc: "Palau", flag: '' },
            { value: "ps", desc: "Palestine", flag: '' },
            { value: "pa", desc: "Panama", flag: '' },
            { value: "py", desc: "Paraguay", flag: '' },
            { value: "pe", desc: "Peru", flag: '' },
            { value: "ph", desc: "Philippines", flag: '' },
            { value: "pn", desc: "Pitcairn Islands", flag: '' },
            { value: "pl", desc: "Poland", flag: '' },
            { value: "pt", desc: "Portugal", flag: '' },
            { value: "pr", desc: "Puerto Rico", flag: '' },
            { value: "qa", desc: "Qatar", flag: '' },
            { value: "re", desc: "Reunion", flag: '' },
            { value: "ro", desc: "Romania", flag: '' },
            { value: "ru", desc: "Russia", flag: '' },
            { value: "rw", desc: "Rwanda", flag: '' },
            { value: "sh", desc: "Saint Helena", flag: '' },
            { value: "kn", desc: "Saint Kitts and Nevis", flag: '' },
            { value: "lc", desc: "Saint Lucia", flag: '' },
            { value: "pm", desc: "Saint Pierre", flag: '' },
            { value: "vc", desc: "Saint Vincent", flag: '' },
            { value: "ws", desc: "Samoa", flag: '' },
            { value: "sm", desc: "San Marino", flag: '' },
            { value: "gs", desc: "Sandwich Islands", flag: '' },
            { value: "st", desc: "Sao Tome", flag: '' },
            { value: "sa", desc: "Saudi Arabia", flag: '' },
            { value: "sn", desc: "Senegal", flag: '' },
            { value: "cs", desc: "Serbia", flag: '' },
            { value: "rs", desc: "Serbia", flag: '' },
            { value: "sc", desc: "Seychelles", flag: '' },
            { value: "sl", desc: "Sierra Leone", flag: '' },
            { value: "sg", desc: "Singapore", flag: '' },
            { value: "sk", desc: "Slovakia", flag: '' },
            { value: "si", desc: "Slovenia", flag: '' },
            { value: "sb", desc: "Solomon Islands", flag: '' },
            { value: "so", desc: "Somalia", flag: '' },
            { value: "za", desc: "South Africa", flag: '' },
            { value: "kr", desc: "South Korea", flag: '' },
            { value: "es", desc: "Spain", flag: '' },
            { value: "lk", desc: "Sri Lanka", flag: '' },
            { value: "sd", desc: "Sudan", flag: '' },
            { value: "sr", desc: "Suriname", flag: '' },
            { value: "sj", desc: "Svalbard", flag: '' },
            { value: "sz", desc: "Swaziland", flag: '' },
            { value: "se", desc: "Sweden", flag: '' },
            { value: "ch", desc: "Switzerland", flag: '' },
            { value: "sy", desc: "Syria", flag: '' },
            { value: "tw", desc: "Taiwan", flag: '' },
            { value: "tj", desc: "Tajikistan", flag: '' },
            { value: "tz", desc: "Tanzania", flag: '' },
            { value: "th", desc: "Thailand", flag: '' },
            { value: "tl", desc: "Timorleste", flag: '' },
            { value: "tg", desc: "Togo", flag: '' },
            { value: "tk", desc: "Tokelau", flag: '' },
            { value: "to", desc: "Tonga", flag: '' },
            { value: "tt", desc: "Trinidad", flag: '' },
            { value: "tn", desc: "Tunisia", flag: '' },
            { value: "tr", desc: "Turkey", flag: '' },
            { value: "tm", desc: "Turkmenistan", flag: '' },
            { value: "tv", desc: "Tuvalu", flag: '' },
            { value: "ug", desc: "Uganda", flag: '' },
            { value: "ua", desc: "Ukraine", flag: '' },
            { value: "ae", desc: "United Arab Emirates", flag: '' },
            { value: "us", desc: "United States", flag: '' },
            { value: "uy", desc: "Uruguay", flag: '' },
            { value: "um", desc: "Us Minor Islands", flag: '' },
            { value: "vi", desc: "Us Virgin Islands", flag: '' },
            { value: "uz", desc: "Uzbekistan", flag: '' },
            { value: "vu", desc: "Vanuatu", flag: '' },
            { value: "va", desc: "Vatican City", flag: '' },
            { value: "ve", desc: "Venezuela", flag: '' },
            { value: "vn", desc: "Vietnam", flag: '' },
            { value: "wf", desc: "Wallis and Futuna", flag: '' },
            { value: "eh", desc: "Western Sahara", flag: '' },
            { value: "ye", desc: "Yemen", flag: '' },
            { value: "zm", desc: "Zambia", flag: '' },
            { value: "zw", desc: "Zimbabwe", flag: '' }


        ];



        return new Observable(observer => {
            observer.next(cntFlagArr);
            observer.complete();
        });
    }

    getListOfWomenCatagory(): Observable<any> {
        const womenCatArr: { value: string, desc: string}[] = [

            { value: "Dresses", desc: "Dresses"},
            { value: "Tops", desc: "Tops"},
            { value: "Trousers", desc: "Trousers"},
            { value: "Leggins", desc: "Leggins"},
            { value: "Shorts", desc: "Shorts"},
            { value: "Shoes", desc: "Shoes"},
            { value: "Swimwear", desc: "Swimwear"},
            { value: "Lingerie", desc: "Lingerie"},
            { value: "Sleepwear", desc: "Sleepwear"},                              
            { value: "Coats", desc: "Coats"},
            { value: "Jackets", desc: "Jackets"},
            { value: "Accessories", desc: "Accessories"},
            { value: "Maternity", desc: "Maternity"},
            { value: "Coats", desc: "Coats"}
           
        ];

        return new Observable(observer => {
            observer.next(womenCatArr);
            observer.complete();
        });
    }

    getListOfMenCatagory(): Observable<any> {
        const womenCatArr: { value: string, desc: string}[] = [

           
            { value: "Shirts", desc: "Shirts"},
            { value: "Trousers", desc: "Trousers"},
            { value: "Shorts", desc: "Shorts"},
            { value: "Shoes", desc: "Shoes"},
            { value: "Swimwear", desc: "Swimwear"},
            { value: "Sleepwear", desc: "Sleepwear"},                              
            { value: "Coats", desc: "Coats"},
            { value: "Jackets", desc: "Jackets"},
            { value: "Underwear", desc: "Underwear"},
            { value: "Coats", desc: "Coats"}
           
        ];

        return new Observable(observer => {
            observer.next(womenCatArr);
            observer.complete();
        });
    }



}
